### ISSUE TITLE
Compatibility issue with 'django-rest-auth' package

### ISSUE THREAD

**Issue by blakey22** [limdauto/drf_openapi#60]
* DRF OpenAPI version: 1.0 (installed from pypi)
* Python version: 2.7
* Operating System: macOS Sierra 10.12.4

### Description

When enabling 'django-rest-auth' package (v0.9.1) with drf, drf_openapi UI cannot be rendered and throw a Traceback to console.

### What I Did

```
2017-10-05 15:50:05,213 [ERROR  ] django.request - Internal Server Error: /v1/schema/
Traceback (most recent call last):
  File "/Users/blake/service/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/blake/service/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/blake/service/venv/lib/python2.7/site-packages/channels/handler.py", line 243, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "/Users/blake/service/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Users/blake/service/venv/lib/python2.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/Users/blake/service/venv/lib/python2.7/site-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/blake/service/drf_openapi/codec.py", line 113, in render
    return OpenAPICodec().encode(data, extra=extra)
  File "/Users/blake/service/drf_openapi/codec.py", line 103, in encode
    return force_bytes(json.dumps(data))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: u'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.' is not JSON serializable
```
1. Install 'django-rest-auth' package and enable it in the urls.py
2. Login as superuser via Django Admin Console
3. Back to drf_openapi UI and the page will not be rendered, error message is shown as above.

**Comment by blakey22** [comment]
I have made a fix for that, please check it out. :)
https://github.com/limdauto/drf_openapi/pull/61
