### ISSUE TITLE
Fix compatibility with DRF 3.7

### ISSUE THREAD

**Issue by limdauto** [limdauto/drf_openapi#64]
Hehehe, ironically enough this project isn't compatible with DRF 3.7

**Comment by bigblind** [comment]
Any idea what it would take to fix this? When running with 3.7.1, I get:

```
Traceback (most recent call last):
  File "/Users/frederikcreemers/.virtualenvs/logflights/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Users/frederikcreemers/.virtualenvs/logflights/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/Users/frederikcreemers/.virtualenvs/logflights/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/frederikcreemers/.virtualenvs/logflights/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/frederikcreemers/.virtualenvs/logflights/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/frederikcreemers/.virtualenvs/logflights/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/Users/frederikcreemers/.virtualenvs/logflights/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/Users/frederikcreemers/.virtualenvs/logflights/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/Users/frederikcreemers/.virtualenvs/logflights/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/frederikcreemers/.virtualenvs/logflights/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/frederikcreemers/.virtualenvs/logflights/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/frederikcreemers/.virtualenvs/logflights/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/frederikcreemers/dev/logflights/logflights/urls.py", line 27, in <module>
    url(r'^api/docs/', include('drf_openapi.urls')),
  File "/Users/frederikcreemers/.virtualenvs/logflights/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/frederikcreemers/.virtualenvs/logflights/lib/python2.7/site-packages/drf_openapi/urls.py", line 3, in <module>
    from drf_openapi.views import SchemaView
  File "/Users/frederikcreemers/.virtualenvs/logflights/lib/python2.7/site-packages/drf_openapi/views.py", line 7, in <module>
    from drf_openapi.entities import OpenApiSchemaGenerator
  File "/Users/frederikcreemers/.virtualenvs/logflights/lib/python2.7/site-packages/drf_openapi/entities.py", line 14, in <module>
    from rest_framework.schemas import SchemaGenerator, insert_into, get_pk_description, field_to_schema
ImportError: cannot import name insert_into
```

I'm willing to look into this, if you're not already doing so. But since you're the author of the code, you may be able to give me some pointers on where to start looking.
